config/routes.rb
Rails.application.routes.draw do
  # Devise for authentication
  devise_for :users, :controllers => { :registrations => "user_registrations" }

  # Nested resource of comments is a subset of products
  resources :products do
    resources :comments
  end

  # A resource route maps a number of related requests to actions in a single controller
  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]

  #syntax = HTTP verb (for example 'get'), path (Controller#Action)
  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/landing_page'

  post 'static_pages/thank_you'
  post 'payments/create'

  # Action cable
  mount ActionCable.server => '/cable'

  #syntax = root "controller#view"
  root "static_pages#landing_page"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def landing_page
    @products_limited = Product.limit(3)
    @products = Product.all
    #@featured_product = Product.first
  end


  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    ActionMailer::Base.mail(:from => @email,
      :to => 'yorgos@berlin.com',
      :subject => "A new contact form message from #{@name}",
      :body => @message).deliver_now
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<!-- <p> Find me in app/views/static_pages/about.html.erb </p> -->
<section class="container anchor" id="about">

  <% cache do %>
    <header class="about-header">
      <h1>About</h1>
    </header><!--End of about header-->

    <div class="row">
      <h3>What</h3>
      <p>Roof party ennui kickstarter keytar mustache, cold-pressed brooklyn. XOXO humblebrag messenger bag offal cronut lo-fi. Small batch tacos you probably haven't heard of them cray. Pinterest selfies swag pug, taxidermy shoreditch fingerstache. Authentic chicharrones pinterest iPhone aesthetic organic. Tattooed iPhone lomo, tote bag ennui chartreuse swag skateboard salvia offal heirloom bespoke. Waistcoat yuccie locavore flannel, vinyl messenger bag tilde chillwave meh. </p>

      <h3>How</h3>
      <p>Roof party ennui kickstarter keytar mustache, cold-pressed brooklyn. XOXO humblebrag messenger bag offal cronut lo-fi. Small batch tacos you probably haven't heard of them cray. Pinterest selfies swag pug, taxidermy shoreditch fingerstache. Authentic chicharrones pinterest iPhone aesthetic organic. Tattooed iPhone lomo, tote bag ennui chartreuse swag skateboard salvia offal heirloom bespoke. Waistcoat yuccie locavore flannel, vinyl messenger bag tilde chillwave meh. </p>

      <h3>History</h3>
      <p>Roof party ennui kickstarter keytar mustache, cold-pressed brooklyn. XOXO humblebrag messenger bag offal cronut lo-fi. Small batch tacos you probably haven't heard of them cray. Pinterest selfies swag pug, taxidermy shoreditch fingerstache. Authentic chicharrones pinterest iPhone aesthetic organic. Tattooed iPhone lomo, tote bag ennui chartreuse swag skateboard salvia offal heirloom bespoke. Waistcoat yuccie locavore flannel, vinyl messenger bag tilde chillwave meh. </p>
    </div><!-- /row -->
  <% end %><!-- /cache -->

</section><!-- /about-->

app/views/static_pages/contact.html.erb
<!-- <p> Find me in app/views/static_pages/contact.html.erb </p> -->
<section class="container anchor" id="contact">

  <% cache do %>

    <header class="contact-header">
      <h1>Contact</h1>
    </header>

    <div class="row">

      <!--Address-->
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="address">
          <h3>Contact details</h3>
          <p class="address-details">
            <span class="glyphicon glyphicon-envelope"></span> &thinsp; example [at] berlin.com
            <br>
            <span class="glyphicon glyphicon-earphone"></span> &thinsp; +49 (0)30 1234 5678
            <br>
            <a href="https://www.google.gr/maps/place/Brandenburg+Gate/@52.5162746,13.377704,15z/data=!4m5!3m4!1s0x0:0x26bbfb4e84674c63!8m2!3d52.5162746!4d13.377704"><span class="glyphicon glyphicon glyphicon-map-marker"></span> &thinsp; Brandenburger Gate</a>
            <br>&thinsp;Pariser Platz
            <br>&thinsp;10117 Berlin
            <br>&thinsp;Germany
          </p>
        </div><!-- /address -->
      </div><!-- /col -->

      <!-- Contact form -->
      <%= flash[:notice] %>
      <%= form_tag("/static_pages/thank_you") do %>
        <div class="col-lg-8 col-md-8 col-sm-10 col-xs-12">
          <div class="form">
            <h3>Contact form</h3>
            <br>
            <div class="form-group">
              <%= label_tag :name %>
              <%= text_field_tag :name, nil, class:"form-control", placeholder:"Enter Name", required:"true" %>
            </div>

            <div class="form-group">
              <%= label_tag :email, "Email Address" %>
              <%= text_field_tag :email, nil, class:"form-control", placeholder:"Enter Email", required:"true" %>
            </div>

            <div class="form-group">
              <%= label_tag :message %>
              <%= text_area_tag :message, nil, class:"form-control message-box", placeholder:"Enter Message", required:"true" %>
            </div>
              <%= submit_tag "Send", class: "btn btn-primary" %>
            <br>
          </div><!-- /form -->
        </div><!-- /col -->
      <% end %><!-- /form -->
    </div><!-- /row -->
  <% end %><!-- /cache -->

</section><!-- /contact -->

app/views/static_pages/index.html.erb
<!-- <p> Find me in app/views/static_pages/index.html.erb </p> -->
<section class="container anchor" id="index-page">

  <% cache do %>
    <h1>Welcome to Flat Tire</h1>
    <h2>Some of the best bicycles in the world, slightly used.</h2>
    <%= image_tag("racebike.jpg", class: "home-img img-responsive") %>
  <% end %><!-- cache -->
  
</section>

app/views/static_pages/landing_page.html.erb
<section class="container anchor" id="landing-page">

  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="margin: 0 auto">
    <% cache do %>
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% @products.each do |product| %>
        <li data-target="#carousel-example-generic" data-slide-to= "<%= @products %>" class="<%= 'active' if product == @products.first %>"></li>
        <% end %>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <% @products_limited.each do |product| %>
          <div class="item <%= 'active' if product == @products_limited.first %>">
            <div class="carousel-caption">
              <h1><%= product.name %></h1>
            </div>
            <%= image_tag(product.image_url, class:"img-responsive")%>
          </div>
        <% end %>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    <% end %><!-- /cache -->
  </div><!-- /carousel -->

</section><!-- /container -->

app/views/static_pages/thank_you.html.erb
<section class="container anchor" id="thank-you">

  <header class="thank-you-header">
    <h1>Thank you!</h1>
  </header><!--End of contact-header-->

  <div class="panel panel-default">
    <div class="panel-body">
      <div class="col-md-6 col-sm-12">
        <%=image_tag("received.png", alt: "Your message was sent", class:"img-responsive")%>
      </div>

      <div class="col-md-6 col-sm-12">
        <h2>Your message was sent. We will get back to you as soon as possible.</h2>
        <%= link_to 'Back to our Products', products_url, class: "btn btn-default"%>
      </div>
    </div><!-- / panel-body -->
  </div><!-- / panel -->

</section>