config/routes.rb
Rails.application.routes.draw do
  # Devise for authentication
  devise_for :users, :controllers => { :registrations => "user_registrations" }

  # Nested resource of comments is a subset of products
  resources :products do
    resources :comments
  end

  # A resource route maps a number of related requests to actions in a single controller
  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]

  #syntax = HTTP verb (for example 'get'), path (Controller#Action)
  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/landing_page'

  post 'static_pages/thank_you'
  post 'payments/create'

  # Action cable
  mount ActionCable.server => '/cable'

  #syntax = root "controller#view"
  root "static_pages#landing_page"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  # All new products are required to have a name
  validates :name, presence: true

  # Database relationships
  # One product may be referenced by several orders because there might be a number of them in stock and multiple customers will want the same product. This is called a has_many relationship, as in “Product model has many orders”
  has_many :orders
  has_many :comments

  # Method that selects the highest rating comment form the comments model using the scope :rating_desc inside the comments model
  def highest_rating_comment
    comments.rating_desc.first
  end

  # Method that selects the lowest rating comment form the comment model using the scope :rating_asc inside the comment model
  def lowest_rating_comment
    comments.rating_asc.first
  end

  # Method that extracts an average rating from the comments
  # The .average method always returns a floating point (A Ruby BigDecimal object)
  # With the .to_f method we are extracting the numerical value from the BigDecimal
  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    # Conditional search. Depending on the environment where the search is applied at (production vs development) we use a diferent SQL matching method
    # the LIKE sql method is case sensitive in the development environment
    # the ILIKE sql method is not case sensitive and it is going to be used for the production environment
    # If there is no search then all the products are going to be displayed.
    if Rails.env.development? && params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    elsif Rails.env.production? && params[:q]
      search_term = params[:q]
      @products = Product.where("name ILIKE ?", "%#{search_term}%")
    else
      # Here we create an instance variable @products
      # and we asign to it all the contents of the array Product which is in the model
      # in order to be able to reference it in the dynamic html views
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :colour, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}-#{params[:q]}"
  end

end

app/views/products/_comments.html.erb
<div class="list-of-comments">
  <!-- Highest Rating Comment.
  see the scope in models/product.rb > scope :rating_desc, -> {order(rating: :desc)}
  and the method highest_rating_comment defined inside the models/comment.rb
  -->
  <div class="col-sm-12 col-md-4">

    <!-- highest rating review -->
    <% if @product.highest_rating_comment %>
      <h2> Highest Rating Review </h2>
      <p>
        &nbsp;
        <!-- review body -->
        <blockquote>
          <p><%= @product.highest_rating_comment.body%></p>
          <br>
          <div class="rated" data-score="<%= @product.highest_rating_comment.rating %>"></div>
        </blockquote>
      </p>
      <br>
    <% end %><!-- /if -->

    <!-- lowest rating review -->
    <% if @product.lowest_rating_comment %>
      <h2> Lowest Rating Review </h2>
      <p>
        &nbsp;
        <!-- review body -->
        <blockquote>
          <p><%= @product.lowest_rating_comment.body %></p>
          <br>
          <div class="rated" data-score="<%= @product.lowest_rating_comment.rating %>"></div>
        </blockquote>
      </p>
      <br>
    <% end %><!-- /if -->

  </div><!-- /col -->

  <div class="col-sm-12 col-md-4">
    <h2> All the Reviews </h2>
    <% @comments.each do |comment| %>
      <div class="product-reviews">

        <br>
        <strong><%= comment.user.first_name %></strong>
        <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
        <!-- space -->
        &nbsp;

        <!-- destroy with admin conditional -->
        <% if signed_in? && current_user.admin? %>
          <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>

        <!-- review body -->
        <blockquote>
          <p><%= comment.body %></p>
          <br>
          <div class="rated" data-score="<%= comment.rating %>"></div>
        </blockquote>

      </div><!-- /product-reviews -->
    <% end %><!-- loop -->

    <!-- pagination -->
    <div class="pagination">
      <%= will_paginate @comments %>
    </div>

  </div><!-- /col -->

</div><!-- /list-of-comments -->

app/views/products/_new_comment.html.erb
<div class="add-your-review">
  <div class="col-sm-12 col-md-4">
    <% if signed_in? %>
      <h3>Add your review </h3>
      <br>
      <!-- The parameter "remote: true" is added for AJAX -->
      <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
        <p>
          <%= f.label :body, "Your comment:" %><br>
          <%= f.text_area :body, class:"form-control"%>
        </p>
        <br>
        <p>
          <%= f.label :rating, "Your rating:"%>
          <!-- Instead of the f.text_field :rating, class: "rating form-control",
          the jquery plugin 'raty' only needs a class named rating in order to work -->
          <div class="rating"></div>
        </p>
        <br>
        <p>
          <%= f.submit class:"btn btn-default" "Submit" %>
        </p>
        <br>
      <% end %>
    <% end %><!-- /contidional -->
  </div><!-- /col -->
</div><!-- /add-your-review -->

app/views/products/edit.html.erb
<header class="edit-product-header">
  <h1>Editing Product</h1>
</header><!--/ edit product-->

<div class="container">
  <div class="row edit-product-form"
    <%= render 'shared/form', product: @product %>
    <%= link_to 'Back', products_path, class:"btn btn-default" %>
    <%= link_to 'Show', @product, class:"btn btn-default"%>
  </div>
</div><!-- / container-->

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<header class="products-header">
  <h1>Products</h1>
</header>

<div class="container">

  <!-- Option to create new product if user is an admin -->
  <% if signed_in? && current_user.admin? %>
    <p>
      <%= link_to 'Create New Product', new_product_path, class:"btn btn-default"%>
    </p>
  <% end %>

  <br>

  <div class="row">
    <!-- Goes to the index method of the products controller
    and takes the instance variable @products
    where we have assigned all the contents of the product array -->
    <% cache(cache_key_for_products) do %>
      <% @products.each do |product| %>
          <%= render partial: 'shared/product', locals: {product: product} %>
      <% end %><!-- /loop -->
    <% end %><!-- /cache -->
  </div>

  <br>

</div><!-- /container -->

app/views/products/new.html.erb
<header class="new-product-header">
  <h1>Creating a New Product</h1>
</header><!--/ new product-->

<div class="container">
  <div class="row new-product-form">
    <%= link_to 'Back', products_path, class:"btn btn-default"%>
    <%= render 'shared/form', product: @product %>
  </div>
</div><!-- /container-->

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container show-product-body">
  <% cache @product do %>
    <div class="row" data-product-id="<%= @product.id %>">
      <div class="col-sm-12 col-md-6">
        <br>
        <br>
        <h3><%= @product.name %></h3>
        <div>
          <%= image_tag(@product.image_url, class: "img-zoom img-responsive", data_zoom_image: "@product.image_url") %>
        </div>
      </div><!-- /col -->
      <div class="col-sm-12 col-md-6">
        <br>
        <br>
        <br>
        <h4>
          <strong>Price:</strong>
          <%= number_to_currency(@product.price, unit:"€") %>
        </h4>
        <br>
        <h4>
          <strong>Colour:</strong>
          <%= @product.colour %>
        </h4>
        <br>
        <h4>
          <strong>Description:</strong>
          <%= @product.description %>
        </h4>
        <br>
        <h4><strong>Average Rating:</strong></h4>
        <div id="average-rating" class="rated" data-score="<%= @product.average_rating %>"></div>
        <br>
        <br>
        <!-- Stripe Checkout -->
        <%= form_tag "/payments/create" do %>
          <p>
            <!-- making product_id accessible to the parameters in order to be able to access the product in the payments controller -->
            <%= hidden_field_tag(:product_id, @product.id) %>
            <%= render partial: "shared/stripe_checkout_button" %>
          <p>
        <% end %>
        <br>
        <p>
          <%= link_to 'Back', products_path, class:"btn btn-default" %>
          <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-default"%>
        </p>

      </div><!-- /col -->
    </div><!-- /row -->
  <% end %><!-- /cache -->

  <div class="row">
    <!-- ActionCable alert for new comment -->
    <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>

    <!-- Rendering partials -->
    <div class="product-reviews-wrapper">
      <%= render 'comments' %>
    </div>

    <%= render 'new_comment'%>
  </div><!-- /row -->

  <!-- elevateZoom - A jQuery image zoom plugin -->
  <script>
    $('#zoom_01').elevateZoom();
  </script>

</div><!-- /container-->