config/routes.rb
Rails.application.routes.draw do
  # Devise for authentication
  devise_for :users, :controllers => { :registrations => "user_registrations" }

  # Nested resource of comments is a subset of products
  resources :products do
    resources :comments
  end

  # A resource route maps a number of related requests to actions in a single controller
  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]

  #syntax = HTTP verb (for example 'get'), path (Controller#Action)
  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/landing_page'

  post 'static_pages/thank_you'
  post 'payments/create'

  # Action cable
  mount ActionCable.server => '/cable'

  #syntax = root "controller#view"
  root "static_pages#landing_page"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Flat Tire Berlin</title>
    <%= csrf_meta_tags %>

    <!--Linking CSS from Bootstrap CDN-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!--Linking CSS from local file-->
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

    <!--Linking Javascript from this file to the application.js file under javascripts-->
    <!-- <%#= javascript_include_tag 'application', 'data-turbolinks-track': true %> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

    <!-- Linking Javascript from Bootstrap CDN after we load the local Javascript as the remote requires jquery which is loaded from the local file-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <!-- Including the meta tag that allowes the app to act responsively to mobile phones -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Linking google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">

    <!-- Linking font awesome -->
    <!-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    -->

  </head>

  <body>
    <div id="wrap">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "FLAT TIRE", static_pages_index_path, class: "navbar-brand" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">
              <!--Instead of <a href="#">Products</a>-->
              <li><%= link_to "PRODUCTS", products_path, class: "navigation-link" %></li>
              <!--Instead of <a href="#">About</a>-->
              <li><%= link_to "ABOUT", static_pages_about_path, class: "navigation-link"%></li>
              <!--Instead of <a href="#">Contact</a>-->
              <li><%= link_to "CONTACT", static_pages_contact_path, class: "navigation-link" %></li>
              <!-- Sign-in, Login, Logout -->
              <li>
                <% if user_signed_in? %>
                  <%= link_to("Log out", destroy_user_session_path, :method => :delete, class:"btn btn-default login-link") %>
                <% else %>
                  <%= link_to("Log in", new_user_session_path, class:"btn btn-default login-link") %>
                <% end %>
              </li>
            </ul>

            <!-- Search form -->
              <%= form_tag("/products", method: "get", id: "search-form", class:"navbar-form navbar-right", role:"search") do %>
                <!--<%= label_tag(:q, "Search for") %> -->
                <%= text_field_tag :q, nil, class:"form-control", placeholder:"Product name..." %>
                <%= button_tag(type: 'submit', class: "btn glyphicon glyphicon-search") do %>
                  <i class="icon icon-search"></i>
                <% end %>
              <% end %>

          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div><!--/wrap-->

    <!-- These two tags display a welcome message when a user signs in -->
    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% elsif alert %>
      <p id="alert" class="alert alert-warning"><%= alert %></p>
    <% end %>

    <%= yield %>

    <footer class="footer-distributed">
      <div class="container">
        <div class="footer-left">
          <p class="footer-links">
            <%= link_to "Home", static_pages_index_path %>
            <%= link_to "Products", products_path %>
            <%= link_to "About", static_pages_about_path %>
            <%= link_to "Contact", static_pages_contact_path %>
          </p>
          <p>&copy; 2016 Flat Tire GmbH</p>
        </div><!-- /footer-left -->
      <div class="footer-margin">
    </footer>

  </body>
</html>